/* This file was generated by the Hex-Rays decompiler version 9.0.0.240807.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_180D85990(__int64 a1, unsigned __int64 a2, char a3);
void __fastcall sub_180D86021(__int64 _RCX, __int64 a2, __int64 a3, char a4);
void __fastcall sub_180D87205();
void __fastcall sub_180D88761(char _CL, __int64 a2, char _R8);
void __fastcall sub_180D8D966(__int64 a1, __int64 a2, __int64 a3, char *a4);
void __fastcall sub_180D95B02();
void __fastcall sub_180D972CB(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7);
void __fastcall sub_180D9784D();
void __fastcall sub_180D9D2A0();
void __fastcall sub_180D9E4E5();
void __fastcall sub_180DA1944();
void __fastcall sub_180DA1D2F(unsigned int a1, __int64 a2, char *a3, __int64 a4);
void __fastcall sub_180DA8AB7(char _CL);
void __fastcall sub_180DABDD2(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26, int a27, int a28, int a29, int a30, int a31, int a32, int a33, int a34, int a35, int a36, int a37, int a38, char a39, char a40);
void __fastcall sub_180DB2639(__int64 a1, __int64 a2, __int64 (__fastcall *a3)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD), __int64 (__fastcall *a4)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD));
void __fastcall sub_180DB5500();
void __fastcall sub_180DB7D82();
void sub_180DBB4D7();
void __fastcall sub_180DBB85F(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
void sub_180DBD4DC();
void sub_180DBF1F7();
void __fastcall sub_180DC2506();
void __fastcall sub_180DC3248();
__int64 __fastcall sub_180DC425A(__int64 a1, int a2);
void __fastcall sub_180DC64D5();
void __fastcall sub_180DCA191();
void __fastcall sub_180DCB06B();
void __fastcall sub_180DCB12D();
__int64 __fastcall sub_180DCB281(); // weak
void __fastcall sub_180DCB33A();
void __fastcall sub_180DCC417(char _CL);
void __fastcall sub_180DCDA82();
void __fastcall sub_180DCE654(__int64 a1, __int64 a2, unsigned __int64 a3);
void __fastcall sub_180DD0E5B(__int64 a1, unsigned int a2, __int64 (__fastcall *a3)(_QWORD, _QWORD, _QWORD), char *a4);
void __fastcall sub_180DD16DB();
__int64 __fastcall sub_180DD2D49(); // weak
void __fastcall sub_180DD7022(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void __fastcall sub_180DD7A4A(int a1, __int64 a2, unsigned __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24);
void __fastcall sub_180DDA7D8(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7);
void __fastcall sub_180DDB0F9(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void __fastcall sub_180DDC59C();
void __fastcall sub_180DDDC7B(__int64 a1, __int64 a2, __int64 a3);
void __fastcall sub_180DDE198();
__int64 __fastcall sub_180DE086F(); // weak
void __fastcall sub_180DE3DA4();
void __fastcall sub_180DE4B60();
__int64 __fastcall sub_180DE4ECD(); // weak
void __fastcall sub_180DE6ED9(__int64 a1, __int64 a2, int a3);
void __fastcall sub_180DEC7BC();
void __fastcall sub_180DEE21C();
void __fastcall sub_180DF3DBD(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall sub_180DF4BC6(int a1, __int64 a2, __int64 a3);
void __fastcall sub_180DF7D98(__int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37);
void sub_180DF8F0F();
void __fastcall sub_180E00F3F(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void __fastcall sub_180E05056();
void __fastcall sub_180E09EC0(__int64 a1, unsigned int a2);
void __fastcall sub_180E0C18A();
void sub_180E0C804();
void __fastcall sub_180E0E8D8(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26, int a27, int a28, int a29, int a30, int a31, int a32, int a33, int a34, int a35, int a36, int a37, int a38, char a39, char a40);
void __fastcall sub_180E0FFD0();
void __fastcall sub_180E10B2C(__int64 a1, __int64 a2, char a3);
void __fastcall sub_180E17CCB();
void sub_180E19528();
void __fastcall sub_180E1B43F();
void __fastcall sub_180E1B57A(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void sub_180E1BA51();
void sub_180E1BB42();
void __fastcall sub_180E1F45D(__int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37);
void sub_180E2247E();
void sub_180E29E14();
void sub_180E2DE61();
void sub_180E300E2();
void sub_180E323B7();
void sub_180E33591();
void __fastcall sub_180E36C7F();
void sub_180E38C08();
void __fastcall sub_180E3BB23();
void __fastcall sub_180E3C2D6();
void __fastcall sub_180E3F161(unsigned int a1, __int64 a2);
__int64 __fastcall sub_180E4C7A1(); // weak
void __fastcall sub_180E4CDE1(int a1);
void __fastcall sub_180E4E16F(int a1, __int64 a2, __int64 a3);
void __fastcall sub_180E55EE3(unsigned __int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, __int64 a11);
void __fastcall sub_180E5810D(__int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37);
void __fastcall sub_180E59597();
void __fastcall sub_180E5CB5C();
void __fastcall sub_180E628D2(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void sub_180E637A5();
__int64 __fastcall sub_180E6A9C0(); // weak
void __fastcall sub_180E72310(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void __fastcall sub_180E742B6();
void sub_180E747D6();
void __fastcall sub_180E74C2B(__int64 a1, __int64 a2, __int64 a3);
void __fastcall sub_180E7A023();
void __fastcall sub_180E7FB71(__int64 a1, int a2, unsigned __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37);
__int64 __fastcall sub_180E80D06(); // weak
void __fastcall sub_180E8442C(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, __int64 a11);
__int64 __fastcall sub_180E85093(int a1, __int64 a2, __int64 a3);
void __fastcall sub_180E85DDE(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, __int64 a12);
void __fastcall sub_180E89304();
void sub_180E89724();
__int64 __fastcall sub_180E89768(); // weak
void __fastcall sub_180E8EA5D(unsigned __int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, int a7, int a8, int a9, int a10, __int64 a11);
void __fastcall sub_180E9D4DD(int a1);
void __fastcall sub_180EA272B();
void __fastcall sub_180EA3D48(__int64 a1, __int64 a2, unsigned __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37);
void sub_180EB5708();
void __fastcall sub_180EB816D(char _CL, __int64 a2, __int64 a3, __int64 (__fastcall **a4)(signed __int64));
void sub_180EC1393();
void __fastcall sub_180EC1720(__int64 a1, __int64 a2, __int64 a3, unsigned __int64 a4, __int64 a5, __int64 a6, __int64 a7, __int64 a8, __int64 a9, __int64 a10, __int64 a11, __int64 a12, __int64 a13, __int64 a14, __int64 a15, __int64 a16, __int64 a17, __int64 a18, __int64 a19, __int64 a20, __int64 a21, __int64 a22, __int64 a23, __int64 a24, __int64 a25, __int64 a26, __int64 a27, __int64 a28, __int64 a29, __int64 a30, __int64 a31, __int64 a32, __int64 a33, __int64 a34, __int64 a35, __int64 a36, __int64 a37, __int64 a38, __int64 a39, __int64 a40);
void sub_180EC4263();
void __fastcall sub_180EC69CC(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7);
__int64 __fastcall nullsub_2(); // weak
__int64 __fastcall sub_180EC6AB5(__int64 a1, _QWORD *a2);

//-------------------------------------------------------------------------
// Data declarations

// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
_UNKNOWN loc_180EA5C5A; // weak


//----- (00000001808B7A05) ----------------------------------------------------
#error "1808B7A05: function frame is wrong (funcsize=0)"

//----- (0000000180D85990) ----------------------------------------------------
__int64 __fastcall sub_180D85990(__int64 a1, unsigned __int64 a2, char a3)
{
  __int64 v7; // rax
  __int64 v8; // r8
  int v9; // r9d
  _DWORD *v10; // rdx
  unsigned int v12; // edx
  int v13; // eax
  int v14; // r11d
  __int64 v15; // r9
  __int64 v16; // rbp
  unsigned __int64 v17; // r10
  char v18; // al
  unsigned __int8 *v19; // r8
  __int64 v22; // r10
  unsigned __int8 v23; // dl
  _BYTE *v28; // rax
  _BYTE *v29; // rbx
  char v30; // cl
  unsigned __int64 v31; // r8
  unsigned __int64 v32; // rcx
  CHAR *v33; // r9
  int v34; // [rsp+20h] [rbp-168h]
  _DWORD *v35; // [rsp+28h] [rbp-160h]
  int v36; // [rsp+30h] [rbp-158h]
  __int64 v37; // [rsp+40h] [rbp-148h]
  CHAR ModuleName[280]; // [rsp+50h] [rbp-138h] BYREF
  __int64 v39; // [rsp+170h] [rbp-18h]
  unsigned int v40; // [rsp+190h] [rbp+8h]
  unsigned int v43; // [rsp+1A8h] [rbp+20h]

  if ( !a1 )
    return 0LL;
  if ( !a2 )
    return 0LL;
  if ( *(_WORD *)a1 != 23117 )
    return 0LL;
  v7 = *(int *)(a1 + 60);
  if ( *(_DWORD *)(v7 + a1) != 17744 )
    return 0LL;
  v8 = *(unsigned int *)(v7 + a1 + 136);
  v36 = v8;
  if ( !(_DWORD)v8 )
    return 0LL;
  v9 = *(_DWORD *)(v7 + a1 + 140);
  v10 = (_DWORD *)(a1 + v8);
  v39 = _RBX;
  _RCX = 0xFFFFFFFFLL;
  v34 = v9;
  v35 = (_DWORD *)(a1 + v8);
  v40 = -1;
  if ( a2 > 0xFFFF )
  {
    v13 = v10[6];
    if ( v13 )
    {
      v14 = v13 - 1;
      LODWORD(_RBX) = 0;
      v15 = a1 + (unsigned int)v10[8];
      v37 = v15;
      if ( v13 - 1 < 0 )
      {
        v9 = v34;
      }
      else
      {
        do
        {
          v16 = 0LL;
          v43 = (v14 + (int)_RBX) >> 1;
          v17 = a2 - *(unsigned int *)(v15 + 4LL * v43);
          v18 = a3;
          v19 = (unsigned __int8 *)(*(unsigned int *)(v15 + 4LL * v43) + a1);
          _R9 = a3;
          __asm { rcl     r9b, cl }
          v22 = v17 - a1;
          do
          {
            v23 = v19[v22];
            _R9 = *v19++;
            if ( v18 )
            {
              v23 ^= (_BYTE)v16 + (unsigned __int8)__ROL4__(1441619553, v16);
              v18 = a3;
              ++v16;
            }
          }
          while ( v23 && v23 == (_BYTE)_R9 );
          if ( v23 < (unsigned __int8)_R9 )
          {
            v10 = v35;
            LOBYTE(_R9) = -108;
            _RCX = v40;
            v14 = v43 - 1;
            __asm { rcr     r9w, 0BFh }
          }
          else if ( v23 <= (unsigned __int8)_R9 )
          {
            v10 = v35;
            LODWORD(_RBX) = v14 + 1;
            _RCX = *(unsigned __int16 *)(a1 + (unsigned int)v35[9] + 2LL * v43);
            v40 = *(unsigned __int16 *)(a1 + (unsigned int)v35[9] + 2LL * v43);
          }
          else
          {
            v10 = v35;
            _RCX = v40;
            LODWORD(_RBX) = v43 + 1;
          }
          v15 = v37;
        }
        while ( (int)_RBX <= v14 );
        LODWORD(v8) = v36;
        v9 = v34;
      }
    }
    if ( (unsigned int)_RCX >= v10[5] )
      return 0LL;
    v12 = *(_DWORD *)(a1 + (unsigned int)v10[7] + 4 * _RCX);
    if ( !v12 )
      return 0LL;
  }
  else
  {
    _RCX = (unsigned int)(a2 - v10[4]);
    if ( (unsigned int)_RCX >= v10[5] )
      return 0LL;
    v12 = *(_DWORD *)((unsigned int)v10[7] + a1 + 4 * _RCX);
    if ( !v12 )
      return 0LL;
  }
  if ( v12 >= (unsigned int)v8 && v12 < v9 + (int)v8 )
  {
    _CL = _RCX + 69;
    __asm { rcr     bl, cl }
    v28 = (_BYTE *)(a1 + v12);
    v29 = v28;
    v30 = *v28;
    if ( *v28 )
    {
      while ( v30 != 46 )
      {
        v30 = *++v29;
        if ( !v30 )
          return 0LL;
      }
      v31 = v29 - v28;
      if ( (unsigned __int64)(v29 - v28) < 0x104 )
      {
        v32 = 0LL;
        if ( v31 )
        {
          v33 = (CHAR *)(ModuleName - v28);
          do
          {
            if ( !*v28 )
              break;
            ++v32;
            v28[(_QWORD)v33] = *v28;
            ++v28;
          }
          while ( v32 < v31 );
        }
        ModuleName[v32] = 0;
        if ( !GetModuleHandleA(ModuleName) )
          JUMPOUT(0x180943C8ALL);
        JUMPOUT(0x180943C98LL);
      }
    }
    return 0LL;
  }
  return v12 + a1;
}
// 180D85ED1: control flows out of bounds to 180943C8A
// 180D85EB6: control flows out of bounds to 180943C98
// 180D85A6D: variable '_RBX' is possibly undefined

//----- (0000000180D86021) ----------------------------------------------------
void __fastcall sub_180D86021(__int64 _RCX, __int64 a2, __int64 a3, char a4)
{
  unsigned __int64 v5; // r8
  __int64 v6; // r9
  char v8; // al
  _BYTE v9[280]; // [rsp+20h] [rbp-118h] BYREF

  _R9 = __ROL1__(__ROR1__(a4, 80), 173);
  __asm { rcr     r9b, 29h }
  v5 = 0LL;
  v6 = _RCX - (_QWORD)v9;
  __asm { rcr     ch, 64h }
  do
  {
    v8 = v9[v5 + v6] ^ (v5 + __ROL4__(1441619553, v5));
    v9[v5] = v8;
    if ( !v8 )
      break;
    ++v5;
  }
  while ( v5 < 0x104 );
  JUMPOUT(0x18098398BLL);
}
// 180D860C9: control flows out of bounds to 18098398B

//----- (0000000180D87205) ----------------------------------------------------
void __fastcall sub_180D87205()
{
  __asm { retn }
}
// 180D87206: unbalanced stack, ignored a potential tail call

//----- (0000000180D88761) ----------------------------------------------------
void __fastcall sub_180D88761(char _CL, __int64 a2, char _R8)
{
  char v4; // r13

  __readeflags();
  _R9 = _BP | (v4 - 29);
  __asm
  {
    rcr     r9b, 0F0h
    rcr     bpl, cl
    rcl     r8b, cl
  }
  sub_180E74C2B(0LL, a2, (__int64)&loc_180EA5C5A);
}
// 180D88771: variable '_BP' is possibly undefined
// 180D8876D: variable 'v4' is possibly undefined

//----- (0000000180D8D966) ----------------------------------------------------
void __fastcall sub_180D8D966(__int64 a1, __int64 a2, __int64 a3, char *a4)
{
  int v4; // eax
  __int64 v6; // rbx
  int v7; // edx
  int v8; // ecx
  signed __int64 v9; // rcx
  unsigned __int64 v10; // rdx
  void *v11; // rsp
  __int64 v15; // [rsp+10h] [rbp-18h] BYREF

  _EDX = v4 >> 31;
  __asm { rcr     dl, 92h }
  v6 = (unsigned int)v4;
  v7 = v4;
  v8 = 0;
  if ( (unsigned int)v4 > 4 )
  {
    v7 = 4;
    v8 = v4 - 4;
  }
  v9 = (unsigned int)(8 * v8);
  v10 = (unsigned int)(8 * v7);
  *((_QWORD *)a4 - 1) = &a4[v10];
  *((_QWORD *)a4 - 2) = &v15;
  v11 = alloca(v9);
  if ( v4 )
  {
    do
    {
      if ( (_DWORD)v6 == 1 )
      {
        v9 = *(_QWORD *)&a4[8 * v6];
      }
      else if ( (_DWORD)v6 == 2 )
      {
        v10 = *(_QWORD *)&a4[8 * v6];
      }
      v6 = (unsigned int)(v6 - 1);
    }
    while ( (_DWORD)v6 );
  }
  **((_QWORD **)a4 - 1) = (*(__int64 (__fastcall **)(signed __int64, unsigned __int64))a4)(v9, v10);
  __asm { retn }
}
// 180D8D966: variable 'v4' is possibly undefined

//----- (0000000180D95B02) ----------------------------------------------------
void __fastcall sub_180D95B02()
{
  __asm { retn }
}
// 180D95B03: unbalanced stack, ignored a potential tail call

//----- (0000000180D972CB) ----------------------------------------------------
void __fastcall sub_180D972CB(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7)
{
  char v7; // di
  __int16 v8; // r10

  _R11 = 15;
  __readeflags();
  __asm { rcr     r11b, 76h }
  _CL = 0;
  LOBYTE(v8) = v7 + v8;
  _R9 = v8;
  __asm
  {
    rcl     r9w, 0EFh
    rcl     r9w, cl
  }
  JUMPOUT(0x180DAF80DLL);
}
// 180D973F5: control flows out of bounds to 180DAF80D
// 180D97339: variable 'v7' is possibly undefined
// 180D97339: variable 'v8' is possibly undefined

//----- (0000000180D9784D) ----------------------------------------------------
void __fastcall sub_180D9784D()
{
  __asm { retn }
}
// 180D9784E: unbalanced stack, ignored a potential tail call

//----- (0000000180D9D2A0) ----------------------------------------------------
void __fastcall sub_180D9D2A0()
{
  __asm { retn }
}
// 180D9D2A1: unbalanced stack, ignored a potential tail call

//----- (0000000180D9E4E5) ----------------------------------------------------
void __fastcall sub_180D9E4E5()
{
  __int64 (*v0)(void); // rax
  __int64 v1; // rbp

  **(_QWORD **)(v1 - 8) = v0();
  sub_180DEC7BC();
}
// 180D9E4E5: could not find valid save-restore pair for rbx
// 180DE9B52: variable 'v0' is possibly undefined
// 180DE9B5D: variable 'v1' is possibly undefined

//----- (0000000180DA1944) ----------------------------------------------------
void __fastcall sub_180DA1944()
{
  __asm { retn }
}
// 180DA1945: unbalanced stack, ignored a potential tail call

//----- (0000000180DA1D2F) ----------------------------------------------------
void __fastcall sub_180DA1D2F(unsigned int a1, __int64 a2, char *a3, __int64 a4)
{
  signed __int64 v4; // rcx
  char v5; // bl
  int v6; // edi
  __int64 v8; // rbx
  int v9; // edx
  int v10; // ecx
  unsigned __int64 v11; // rdx
  void *i; // rsp
  _QWORD v17[3]; // [rsp+10h] [rbp-18h] BYREF

  v17[1] = a4;
  _BL = a4 & v5;
  __asm { rcl     bl, 58h }
  v8 = a1;
  v9 = a1;
  v10 = 0;
  if ( (unsigned int)v8 > 4 )
  {
    v9 = 4;
    v10 = v8 - 4;
  }
  v4 = (unsigned int)(8 * v10);
  v11 = (unsigned int)(8 * v9);
  *((_QWORD *)a3 - 1) = &a3[v11];
  *((_QWORD *)a3 - 2) = v17;
  for ( i = alloca(v4); (_DWORD)v8; v8 = (unsigned int)(v8 - 1) )
  {
    if ( (_DWORD)v8 == 1 )
    {
      v4 = *(_QWORD *)&a3[8 * v8];
    }
    else if ( (_DWORD)v8 == 2 )
    {
      v11 = *(_QWORD *)&a3[8 * v8];
    }
  }
  **((_QWORD **)a3 - 1) = (*(__int64 (__fastcall **)(signed __int64, unsigned __int64))a3)(v4, v11);
  LOBYTE(v6) = 0;
  _EDI = v6 & 0x7FFFFFFF;
  __asm { rcl     dil, 22h }
  LOBYTE(_EDI) = -(char)_EDI;
  __asm
  {
    rcr     edi, 0E0h
    retn
  }
}
// 180DA1D34: variable 'v5' is possibly undefined
// 180DF7213: variable 'v6' is possibly undefined

//----- (0000000180DA8AB7) ----------------------------------------------------
void __fastcall sub_180DA8AB7(char _CL)
{
  __int64 v2; // rdi
  int v4; // edx

  v4 = 1960009304 - ((_ESI ^ *(_DWORD *)(v2 - 4) ^ 0x3BA11C7A) + 1);
  __asm
  {
    rcl     sil, cl
    retn
  }
}
// 180DA8ACD: variable '_ESI' is possibly undefined
// 180DA8ABE: variable 'v2' is possibly undefined

//----- (0000000180DABDD2) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall sub_180DABDD2(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        __int64 a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        char a39,
        char a40)
{
  __int64 v42; // rsi
  int v43; // [rsp+1A0h] [rbp-48h]

  __readeflags();
  __asm { rcr     rbp, 67h }
  v42 = _byteswap_ulong(__ROL4__(v43 - 1, 2)) + 0x100000000LL;
  __asm { jmp     rbp }
}
// 180DADCFA: positive sp value 80 has been found
// 180DABE3A: variable 'v43' is possibly undefined

//----- (0000000180DB2639) ----------------------------------------------------
void __fastcall sub_180DB2639(
        __int64 a1,
        __int64 a2,
        __int64 (__fastcall *a3)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD),
        __int64 (__fastcall *a4)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD))
{
  __int64 v6; // rbp
  char *v7; // r10
  __int64 v8; // rbx
  int v9; // edx
  unsigned __int64 v12; // rdx
  void *v13; // rsp
  _QWORD v17[3]; // [rsp+10h] [rbp-18h] BYREF

  LOBYTE(a3) = ~__ROR1__((_BYTE)a3 - 1, 1);
  LOBYTE(v6) = (unsigned __int8)a3 ^ v6;
  v17[0] = v6;
  v8 = (unsigned int)a3;
  v9 = (int)a3;
  _ECX = 0;
  if ( (unsigned int)a3 > 4 )
  {
    v9 = 4;
    _ECX = (_DWORD)a3 - 4;
    _AX ^= 4u;
    __asm { rcr     ah, cl }
  }
  _RCX = (unsigned int)(8 * _ECX);
  HIBYTE(_AX) = ~HIBYTE(_AX);
  __asm { rcl     ax, cl }
  v12 = (unsigned int)(8 * v9);
  *((_QWORD *)v7 - 1) = &v7[v12];
  *((_QWORD *)v7 - 2) = v17;
  v13 = alloca(_RCX);
  if ( (_DWORD)a3 )
  {
    do
    {
      switch ( (_DWORD)v8 )
      {
        case 1:
          _RCX = *(_QWORD *)&v7[8 * v8];
          break;
        case 2:
          v12 = *(_QWORD *)&v7[8 * v8];
          break;
        case 3:
          a3 = *(__int64 (__fastcall **)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD))&v7[8 * v8];
          break;
        case 4:
          a4 = *(__int64 (__fastcall **)(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD))&v7[8 * v8];
          break;
      }
      v8 = (unsigned int)(v8 - 1);
    }
    while ( (_DWORD)v8 );
  }
  **((_QWORD **)v7 - 1) = (*(__int64 (__fastcall **)(signed __int64, unsigned __int64, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD))v7)(
                            _RCX,
                            v12,
                            a3,
                            a4,
                            v17[0],
                            v17[1],
                            v17[2]);
  __asm { jmp     rdi }
}
// 180DB265A: variable 'v6' is possibly undefined
// 180E907CD: variable 'v7' is possibly undefined
// 180E148DB: variable '_AX' is possibly undefined

//----- (0000000180DB5500) ----------------------------------------------------
void __fastcall sub_180DB5500()
{
  __asm { retn }
}
// 180DB5501: unbalanced stack, ignored a potential tail call

//----- (0000000180DB7D82) ----------------------------------------------------
void __fastcall sub_180DB7D82()
{
  __asm { retn }
}
// 180DB7D83: unbalanced stack, ignored a potential tail call

//----- (0000000180DBB4D7) ----------------------------------------------------
void sub_180DBB4D7()
{
  JUMPOUT(0x180E1E3C3LL);
}
// 180D8EA82: control flows out of bounds to 180E1E3C3

//----- (0000000180DBB85F) ----------------------------------------------------
void __fastcall sub_180DBB85F(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __asm { retn }
}
// 180DBB861: unbalanced stack, ignored a potential tail call

//----- (0000000180DBD4DC) ----------------------------------------------------
void sub_180DBD4DC()
{
  JUMPOUT(0x180DE1E4BLL);
}
// 180E936B5: control flows out of bounds to 180DE1E4B

//----- (0000000180DBF1F7) ----------------------------------------------------
void sub_180DBF1F7()
{
  JUMPOUT(0x180E2F95ELL);
}
// 180E8E9D2: control flows out of bounds to 180E2F95E

//----- (0000000180DC2506) ----------------------------------------------------
void __fastcall sub_180DC2506()
{
  __asm { retn }
}
// 180DC2507: unbalanced stack, ignored a potential tail call

//----- (0000000180DC3248) ----------------------------------------------------
void __fastcall sub_180DC3248()
{
  __int64 v0; // rax
  char v1; // dh

  *(_BYTE *)(v0 - 59) |= v1;
  __asm { sysret }
}
// 180DC324D: control flows out of bounds to 180DC3250
// 180DC324A: variable 'v1' is possibly undefined
// 180DC324A: variable 'v0' is possibly undefined

//----- (0000000180DC425A) ----------------------------------------------------
__int64 __fastcall sub_180DC425A(__int64 a1, int a2)
{
  __int64 v2; // rbp

  return ((__int64 (*)(void))(a2 + v2))();
}
// 180E6AE44: variable 'v2' is possibly undefined

//----- (0000000180DC64D5) ----------------------------------------------------
void __fastcall sub_180DC64D5()
{
  __asm { retn }
}
// 180DC64D6: unbalanced stack, ignored a potential tail call

//----- (0000000180DCA191) ----------------------------------------------------
void __fastcall sub_180DCA191()
{
  __asm { retn }
}
// 180DCA192: unbalanced stack, ignored a potential tail call

//----- (0000000180DCB06B) ----------------------------------------------------
void __fastcall sub_180DCB06B()
{
  __asm { retn }
}
// 180DCB06C: unbalanced stack, ignored a potential tail call

//----- (0000000180DCB12D) ----------------------------------------------------
void __fastcall sub_180DCB12D()
{
  __asm { retn }
}
// 180DCB12E: unbalanced stack, ignored a potential tail call

//----- (0000000180DCB281) ----------------------------------------------------
__int64 __fastcall sub_180DCB281()
{
  __int64 (*v0)(void); // rax
  __int64 v1; // rbp
  __int64 v2; // rax
  int v7; // [rsp+8h] [rbp-18h]
  __int64 v8; // [rsp+10h] [rbp-10h]
  _DWORD *v9; // [rsp+18h] [rbp-8h]

  v2 = v0();
  __asm { rcr     r8b, cl }
  **(_QWORD **)(v1 - 8) = v2;
  return ((__int64 (*)(void))((int)__ROL4__(-_byteswap_ulong((v7 ^ *v9) - 259683496) - 1, 3) + v8))();
}
// 180DD8266: variable 'v0' is possibly undefined
// 180DD8270: variable 'v1' is possibly undefined
// 180E4F65B: variable 'v7' is possibly undefined
// 180DD82AD: variable 'v9' is possibly undefined
// 180E4C30F: variable 'v8' is possibly undefined
// 180DCB281: using guessed type __int64 __fastcall sub_180DCB281();

//----- (0000000180DCB33A) ----------------------------------------------------
void __fastcall sub_180DCB33A()
{
  __asm { retn }
}
// 180DCB33B: unbalanced stack, ignored a potential tail call

//----- (0000000180DCC417) ----------------------------------------------------
void __fastcall sub_180DCC417(char _CL)
{
  int v1; // eax
  __int16 v3; // sp
  int vars0; // [rsp+0h] [rbp+0h]
  int vars0a; // [rsp+0h] [rbp+0h]

  LOWORD(_RBP) = v3;
  __asm { rcl     rbp, cl }
  vars0a = -(v1 + 1) ^ vars0;
  JUMPOUT(0x180E1E3C3LL);
}
// 180D8EA82: control flows out of bounds to 180E1E3C3
// 180DCC42C: variable 'v3' is possibly undefined
// 180DCC417: variable 'v1' is possibly undefined
// 180DCC432: variable 'vars0' is possibly undefined

//----- (0000000180DCDA82) ----------------------------------------------------
void __fastcall sub_180DCDA82()
{
  __int64 (*v0)(void); // rax
  __int64 v1; // rbp

  **(_QWORD **)(v1 - 8) = v0();
  __asm { retn }
}
// 180EC006E: variable 'v0' is possibly undefined
// 180EC0075: variable 'v1' is possibly undefined

//----- (0000000180DCE654) ----------------------------------------------------
void __fastcall sub_180DCE654(__int64 a1, __int64 a2, unsigned __int64 a3)
{
  __int16 v5; // si

  _SI = v5 | 0x4F8B;
  __asm { rcl     si, 0CAh }
  LOWORD(a3) = _byteswap_ushort(a3);
  _R8 = _byteswap_uint64(a3);
  __asm
  {
    rcr     r8w, 50h
    retn
  }
}
// 180DCE65A: variable 'v5' is possibly undefined

//----- (0000000180DD0E5B) ----------------------------------------------------
void __fastcall sub_180DD0E5B(__int64 a1, unsigned int a2, __int64 (__fastcall *a3)(_QWORD, _QWORD, _QWORD), char *a4)
{
  __int64 v4; // rbx
  signed __int64 v5; // rcx
  unsigned __int64 v6; // rdx
  void *i; // rsp
  int v8; // ecx
  __int64 v12; // [rsp+10h] [rbp-18h] BYREF

  v4 = a2;
  v8 = 0;
  if ( a2 > 4 )
  {
    a2 = 4;
    v8 = v4 - 4;
  }
  v5 = (unsigned int)(8 * v8);
  v6 = 8 * a2;
  *((_QWORD *)a4 - 1) = &a4[v6];
  *((_QWORD *)a4 - 2) = &v12;
  for ( i = alloca(v5); (_DWORD)v4; v4 = (unsigned int)(v4 - 1) )
  {
    switch ( (_DWORD)v4 )
    {
      case 1:
        v5 = *(_QWORD *)&a4[8 * v4];
        break;
      case 2:
        v6 = *(_QWORD *)&a4[8 * v4];
        break;
      case 3:
        a3 = *(__int64 (__fastcall **)(_QWORD, _QWORD, _QWORD))&a4[8 * v4];
        break;
    }
  }
  **((_QWORD **)a4 - 1) = (*(__int64 (__fastcall **)(signed __int64, unsigned __int64, _QWORD))a4)(v5, v6, a3);
  __asm { retn }
}

//----- (0000000180DD16DB) ----------------------------------------------------
void __fastcall sub_180DD16DB()
{
  __asm { retn }
}
// 180DD16DC: unbalanced stack, ignored a potential tail call

//----- (0000000180DD2D49) ----------------------------------------------------
__int64 __fastcall sub_180DD2D49()
{
  __int64 v0; // rbx
  int v1; // ebp
  int v2; // r10d

  return ((__int64 (*)(void))((-__ROR4__(_byteswap_ulong(v1 ^ v2) - 1, 3) ^ 0x6D9F5984) + v0))();
}
// 180DD2D49: variable 'v1' is possibly undefined
// 180DD2D49: variable 'v2' is possibly undefined
// 180DD2D74: variable 'v0' is possibly undefined
// 180DD2D49: using guessed type __int64 __fastcall sub_180DD2D49();

//----- (0000000180DD7022) ----------------------------------------------------
void __fastcall sub_180DD7022(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  char v12; // bl
  __int16 v13; // si
  __int16 v15; // sp
  __int16 v16; // di
  __int64 v18; // rbp

  HIBYTE(_R9) = HIBYTE(v13);
  v16 = v15;
  _DI = v16 | (1 << (v12 & 0xF));
  __asm { rcr     di, 22h }
  LOBYTE(_R9) = v13 - 101;
  __asm { rcl     r9w, 0D9h }
  v18 = _byteswap_ulong(_byteswap_ulong((_byteswap_ulong(a12 - 1) ^ 0x3F6427C0) - 1) + 11144834)
      + 927561032
      + 0x100000000LL;
  __asm { jmp     rdi }
}
// 180DD7024: variable 'v13' is possibly undefined
// 180DD7043: variable 'v15' is possibly undefined
// 180DD7086: variable 'v12' is possibly undefined

//----- (0000000180DD7A4A) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall sub_180DD7A4A(
        int a1,
        __int64 a2,
        unsigned __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24)
{
  __int64 v24; // r9
  __int64 *v25; // rdx
  unsigned __int64 v26; // kr00_8
  __int64 v27; // [rsp-50h] [rbp-80h] BYREF

  v24 = a1 + a4;
  if ( a3 > (unsigned __int64)&a24 )
  {
    sub_180DBB85F(a1, a2, a3, v24);
  }
  else
  {
    v25 = (__int64 *)(((a3 - 128) & 0xFFFFFFFFFFFFFFF0uLL) - 256);
    v26 = __readeflags();
    qmemcpy(v25, &v27, 0x100uLL);
    __writeeflags(v26);
    sub_180DBB85F(0LL, (__int64)v25, a3, v24);
  }
}
// 180DD7C0C: positive sp value 68 has been found

//----- (0000000180DDA7D8) ----------------------------------------------------
void __fastcall sub_180DDA7D8(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7)
{
  sub_180EC69CC(a1, a2, a3, a4, a5, a6, a7);
}

//----- (0000000180DDB0F9) ----------------------------------------------------
void __fastcall sub_180DDB0F9(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  unsigned int v12; // r10d
  __int64 v13; // r9
  char v14; // sp
  char v15; // al

  v13 = v12;
  v15 = v14;
  LOBYTE(v13) = v15;
  sub_180E1B57A(a1, a2, a3, v13, a5, a6, a7, a8, a9, a10, a11, a12);
}
// 180DDB112: ignored the value written to the shadow area of the succeeding call
// 180DDB10C: ignored the value written to the shadow area of the succeeding call
// 180DDB10A: ignored the value written to the shadow area of the succeeding call
// 180DDB108: ignored the value written to the shadow area of the succeeding call
// 180DDB101: variable 'v12' is possibly undefined
// 180DDB10F: variable 'v14' is possibly undefined

//----- (0000000180DDC59C) ----------------------------------------------------
void __fastcall sub_180DDC59C()
{
  __asm { retn }
}
// 180DDC59D: unbalanced stack, ignored a potential tail call

//----- (0000000180DDDC7B) ----------------------------------------------------
void __fastcall sub_180DDDC7B(__int64 a1, __int64 a2, __int64 a3)
{
  __asm { retn }
}

//----- (0000000180DDE198) ----------------------------------------------------
void __fastcall sub_180DDE198()
{
  __asm { retn }
}
// 180DDE199: unbalanced stack, ignored a potential tail call

//----- (0000000180DE086F) ----------------------------------------------------
__int64 __fastcall sub_180DE086F()
{
  __int64 (*v0)(void); // rax
  __int64 v1; // rbp
  int v3; // [rsp+8h] [rbp-18h]
  __int64 v4; // [rsp+10h] [rbp-10h]
  __int64 v5; // [rsp+18h] [rbp-8h]

  **(_QWORD **)(v1 - 8) = v0();
  return ((__int64 (*)(void))(__ROL4__(-__ROR4__((v3 ^ *(_DWORD *)(v5 - 4)) - 845030227, 3), 3) + 514916641 + v4))();
}
// 180D9E875: variable 'v0' is possibly undefined
// 180D9E889: variable 'v1' is possibly undefined
// 180E88155: variable 'v3' is possibly undefined
// 180E8813F: variable 'v5' is possibly undefined
// 180E88197: variable 'v4' is possibly undefined
// 180DE086F: using guessed type __int64 __fastcall sub_180DE086F();

//----- (0000000180DE3DA4) ----------------------------------------------------
void __fastcall sub_180DE3DA4()
{
  __asm { retn }
}
// 180DE3DA5: unbalanced stack, ignored a potential tail call

//----- (0000000180DE4B60) ----------------------------------------------------
void __fastcall sub_180DE4B60()
{
  __asm { retn }
}
// 180DE4B61: unbalanced stack, ignored a potential tail call

//----- (0000000180DE4ECD) ----------------------------------------------------
__int64 __fastcall sub_180DE4ECD()
{
  int v1; // eax
  __int64 v2; // rdi

  return ((__int64 (*)(void))(-_byteswap_ulong(v1 ^ 0x2C7E006B) + v2))();
}
// 180DE4ED1: variable 'v1' is possibly undefined
// 180DE4EF3: variable 'v2' is possibly undefined
// 180DE4ECD: using guessed type __int64 __fastcall sub_180DE4ECD();

//----- (0000000180DE6ED9) ----------------------------------------------------
void __fastcall sub_180DE6ED9(__int64 a1, __int64 a2, int a3)
{
  __asm { retn }
}
// 180DE6EE0: unbalanced stack, ignored a potential tail call

//----- (0000000180DEC7BC) ----------------------------------------------------
void __fastcall sub_180DEC7BC()
{
  __asm { retn }
}

//----- (0000000180DEE21C) ----------------------------------------------------
void __fastcall sub_180DEE21C()
{
  __int64 (*v0)(void); // rax
  __int64 v1; // rbp

  **(_QWORD **)(v1 - 8) = v0();
  __asm { retn }
}
// 180DB5E01: variable 'v0' is possibly undefined
// 180DB5E15: variable 'v1' is possibly undefined

//----- (0000000180DF3DBD) ----------------------------------------------------
void __fastcall sub_180DF3DBD(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __asm { retn }
}

//----- (0000000180DF4BC6) ----------------------------------------------------
__int64 __fastcall sub_180DF4BC6(int a1, __int64 a2, __int64 a3)
{
  return ((__int64 (*)(void))(a1 + a3))();
}

//----- (0000000180DF7D98) ----------------------------------------------------
void __fastcall sub_180DF7D98(
        __int64 a1,
        __int64 a2,
        unsigned __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37)
{
  int v37; // r10d
  __int64 v38; // r9

  v38 = v37 + a4;
  if ( a3 <= (unsigned __int64)&a37 )
  {
    __readeflags();
    JUMPOUT(0x180E19F6BLL);
  }
  sub_180DBB85F(a1, a2, a3, v38);
}
// 180E2FB60: control flows out of bounds to 180E19F6B
// 180DF7D98: variable 'v37' is possibly undefined

//----- (0000000180DF8F0F) ----------------------------------------------------
void sub_180DF8F0F()
{
  JUMPOUT(0x180DD641ELL);
}
// 180E26679: control flows out of bounds to 180DD641E

//----- (0000000180E00F3F) ----------------------------------------------------
void __fastcall sub_180E00F3F(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  __getcallerseflags();
  sub_180E85DDE(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
}
// 180E00F3F: ignored the value written to the shadow area of the succeeding call

//----- (0000000180E05056) ----------------------------------------------------
void __fastcall sub_180E05056()
{
  __asm { retn }
}
// 180E05057: unbalanced stack, ignored a potential tail call

//----- (0000000180E09EC0) ----------------------------------------------------
void __fastcall sub_180E09EC0(__int64 a1, unsigned int a2)
{
  __int64 v2; // rdi
  __int64 v3; // r11
  unsigned int v4; // ebx
  unsigned int v5; // ecx
  void *v6; // rsp
  __int64 v7; // [rsp-8h] [rbp-18h] BYREF

  LOBYTE(v2) = a2 ^ v2;
  v7 = v2;
  v4 = a2;
  v5 = 0;
  if ( a2 > 4 )
  {
    a2 = 4;
    v5 = v4 - 4;
  }
  *(_QWORD *)(v3 - 8) = 8 * a2 + v3;
  *(_QWORD *)(v3 - 16) = &v7;
  v6 = alloca(8 * v5);
  if ( v4 )
    JUMPOUT(0x180E9DD12LL);
  JUMPOUT(0x180DFF932LL);
}
// 180E9DD0C: control flows out of bounds to 180E9DD12
// 180E9DD0C: control flows out of bounds to 180DFF932
// 180E09EC0: variable 'v2' is possibly undefined
// 180E9DCDA: variable 'v3' is possibly undefined

//----- (0000000180E0C18A) ----------------------------------------------------
void __fastcall sub_180E0C18A()
{
  __asm { retn }
}
// 180E0C18B: unbalanced stack, ignored a potential tail call

//----- (0000000180E0C804) ----------------------------------------------------
void sub_180E0C804()
{
  JUMPOUT(0x180DE1E4BLL);
}
// 180E936B5: control flows out of bounds to 180DE1E4B

//----- (0000000180E0E8D8) ----------------------------------------------------
void __fastcall sub_180E0E8D8(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        __int64 a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        char a39,
        char a40)
{
  __int64 v40; // rax
  unsigned __int16 v41; // si

  sub_180DABDD2(
    a1,
    v40 >> 63,
    a3,
    v41,
    a5,
    a6,
    a7,
    a8,
    a9,
    a10,
    a11,
    a12,
    a13,
    a14,
    a15,
    a16,
    a17,
    a18,
    a19,
    a20,
    a21,
    a22,
    a23,
    a24,
    a25,
    a26,
    a27,
    a28,
    a29,
    a30,
    a31,
    a32,
    a33,
    a34,
    a35,
    a36,
    a37,
    a38,
    a39,
    a40);
}
// 180E0E8EB: variable 'v40' is possibly undefined
// 180E0E8ED: variable 'v41' is possibly undefined

//----- (0000000180E0FFD0) ----------------------------------------------------
void __fastcall sub_180E0FFD0()
{
  __asm { retn }
}
// 180E0FFD1: unbalanced stack, ignored a potential tail call

//----- (0000000180E10B2C) ----------------------------------------------------
void __fastcall sub_180E10B2C(__int64 a1, __int64 a2, char a3)
{
  __int64 v4; // r8
  __int16 v6; // bp
  int v11; // [rsp+218h] [rbp+8h]

  _CL = a3;
  _R10 = v6;
  __readeflags();
  __asm
  {
    rcr     r10w, cl
    rcr     rax, 15h
  }
  LOBYTE(_R10) = -45;
  _CL = 0;
  __asm { rcr     r10b, cl }
  v4 = (unsigned int)(109668407 - (__ROL4__(v11, 1) + 1)) + 0x100000000LL;
  __asm { retn }
}
// 180E10B49: variable 'v6' is possibly undefined

//----- (0000000180E17CCB) ----------------------------------------------------
void __fastcall sub_180E17CCB()
{
  unsigned __int8 v0; // al
  int v6; // [rsp+218h] [rbp+18h]

  __readeflags();
  _BP = v0;
  __asm
  {
    rcl     bpl, 4Eh
    rcr     rdi, 0AFh
  }
  _RDX = 0x1000000B3LL;
  LOWORD(_RDX) = v0;
  __asm { rcr     rdx, 1Ah }
  _RDI = _byteswap_ulong((__ROL4__(v6, 3) + 1) ^ 0x2F354E69) + 0x100000000LL;
  LODWORD(_RDX) = _byteswap_ulong((((_RDI ^ *(_DWORD *)_RDI) + 1) ^ 0x7D4E4607) - 1865696124);
  __asm
  {
    rcr     dil, 0DDh
    retn
  }
}
// 180E17D16: variable 'v0' is possibly undefined

//----- (0000000180E19528) ----------------------------------------------------
void sub_180E19528()
{
  ;
}

//----- (0000000180E1B43F) ----------------------------------------------------
void __fastcall sub_180E1B43F()
{
  __asm { retn }
}
// 180E1B440: unbalanced stack, ignored a potential tail call

//----- (0000000180E1B57A) ----------------------------------------------------
void __fastcall sub_180E1B57A(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  __int16 v12; // bp

  sub_180E628D2(a1, a2, a3, (unsigned int)v12, a5, a6, a7, a8, a9, a10, a11, a12);
}
// 180E1B584: ignored the value written to the shadow area of the succeeding call
// 180E1B57A: ignored the value written to the shadow area of the succeeding call
// 180E1B585: variable 'v12' is possibly undefined

//----- (0000000180E1BA51) ----------------------------------------------------
void sub_180E1BA51()
{
  JUMPOUT(0x180DB0A18LL);
}
// 180E1BA90: control flows out of bounds to 180DB0A18

//----- (0000000180E1BB42) ----------------------------------------------------
void sub_180E1BB42()
{
  JUMPOUT(0x180DAEF99LL);
}
// 180E1BB45: control flows out of bounds to 180DAEF99

//----- (0000000180E1F45D) ----------------------------------------------------
void __fastcall sub_180E1F45D(
        __int64 a1,
        __int64 a2,
        unsigned __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37)
{
  int v37; // edx
  __int64 v38; // r9
  int v39; // eax
  __int64 v40; // rbx
  int v41; // esi

  *(_DWORD *)(a3 + 4) = v39;
  v37 = __ROR4__(_byteswap_ulong(((v41 ^ *(_DWORD *)(v40 - 4)) - 1843676888) ^ 0x77306601), 2);
  v38 = v37 + a4;
  if ( a3 <= (unsigned __int64)&a37 )
  {
    __readeflags();
    JUMPOUT(0x180E19F6BLL);
  }
  sub_180DBB85F(a1, v37, a3, v38);
}
// 180E2FB60: control flows out of bounds to 180E19F6B
// 180E1F462: variable 'v39' is possibly undefined
// 180D98D80: variable 'v41' is possibly undefined
// 180E1F466: variable 'v40' is possibly undefined

//----- (0000000180E2247E) ----------------------------------------------------
void sub_180E2247E()
{
  JUMPOUT(0x180E2F95ELL);
}
// 180E8E9D2: control flows out of bounds to 180E2F95E

//----- (0000000180E29E14) ----------------------------------------------------
void sub_180E29E14()
{
  JUMPOUT(0x180E2F0FALL);
}
// 180E00092: control flows out of bounds to 180E2F0FA

//----- (0000000180E2DE61) ----------------------------------------------------
void sub_180E2DE61()
{
  JUMPOUT(0x180E2F95ELL);
}
// 180E8E9D2: control flows out of bounds to 180E2F95E

//----- (0000000180E300E2) ----------------------------------------------------
void sub_180E300E2()
{
  sub_180E17CCB();
}

//----- (0000000180E323B7) ----------------------------------------------------
void sub_180E323B7()
{
  JUMPOUT(0x180DB09B3LL);
}
// 180E323C6: control flows out of bounds to 180DB09B3

//----- (0000000180E33591) ----------------------------------------------------
void sub_180E33591()
{
  JUMPOUT(0x180DE1E4BLL);
}
// 180E936B5: control flows out of bounds to 180DE1E4B

//----- (0000000180E36C7F) ----------------------------------------------------
void __fastcall sub_180E36C7F()
{
  __asm { retn }
}
// 180E36C80: unbalanced stack, ignored a potential tail call

//----- (0000000180E38C08) ----------------------------------------------------
void sub_180E38C08()
{
  JUMPOUT(0x180E1E3C3LL);
}
// 180D8EA82: control flows out of bounds to 180E1E3C3

//----- (0000000180E3BB23) ----------------------------------------------------
void __fastcall sub_180E3BB23()
{
  __asm { retn }
}
// 180E3BB24: unbalanced stack, ignored a potential tail call

//----- (0000000180E3C2D6) ----------------------------------------------------
void __fastcall sub_180E3C2D6()
{
  __asm { retn }
}
// 180E3C2D8: unbalanced stack, ignored a potential tail call

//----- (0000000180E3F161) ----------------------------------------------------
void __fastcall sub_180E3F161(unsigned int a1, __int64 a2)
{
  unsigned __int16 v2; // r10

  __readeflags();
  sub_180DCE654(_byteswap_ulong(a1) & 0xFFFFEFFF, a2, v2);
}
// 180E3F1C9: ignored the value written to the shadow area of the succeeding call
// 180E3F1C0: ignored the value written to the shadow area of the succeeding call
// 180E3F1B3: ignored the value written to the shadow area of the succeeding call
// 180E3F1B1: ignored the value written to the shadow area of the succeeding call
// 180E3F1FB: variable 'v2' is possibly undefined

//----- (0000000180E4C7A1) ----------------------------------------------------
__int64 __fastcall sub_180E4C7A1()
{
  int v0; // ebx
  __int64 v1; // rbp

  return ((__int64 (*)(void))(v0 + v1))();
}
// 180E4C7A1: variable 'v0' is possibly undefined
// 180E98B40: variable 'v1' is possibly undefined
// 180E4C7A1: using guessed type __int64 __fastcall sub_180E4C7A1();

//----- (0000000180E4CDE1) ----------------------------------------------------
void __fastcall sub_180E4CDE1(int a1)
{
  __asm { retn }
}

//----- (0000000180E4E16F) ----------------------------------------------------
void __fastcall sub_180E4E16F(int a1, __int64 a2, __int64 a3)
{
  __asm { retn }
}

//----- (0000000180E55EE3) ----------------------------------------------------
void __fastcall sub_180E55EE3(
        unsigned __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        __int64 a11)
{
  sub_180E8EA5D(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11);
}

//----- (0000000180E5810D) ----------------------------------------------------
void __fastcall sub_180E5810D(
        __int64 a1,
        __int64 a2,
        unsigned __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37)
{
  __int64 v37; // r9
  int v38; // eax
  __int64 v39; // rbx
  int v40; // esi
  int v41; // edx

  *(_DWORD *)(a3 + 4) = v38;
  v41 = __ROR4__(_byteswap_ulong(((v40 ^ *(_DWORD *)(v39 - 4)) - 1843676888) ^ 0x77306601), 2);
  v37 = v41 + a4;
  if ( a3 <= (unsigned __int64)&a37 )
  {
    __readeflags();
    JUMPOUT(0x180E19F6BLL);
  }
  sub_180DBB85F(a1, v41, a3, v37);
}
// 180E2FB60: control flows out of bounds to 180E19F6B
// 180E5810D: variable 'v38' is possibly undefined
// 180E5812B: variable 'v40' is possibly undefined
// 180E58119: variable 'v39' is possibly undefined

//----- (0000000180E59597) ----------------------------------------------------
void __fastcall sub_180E59597()
{
  __asm { retn }
}
// 180E59598: unbalanced stack, ignored a potential tail call

//----- (0000000180E5CB5C) ----------------------------------------------------
void __fastcall sub_180E5CB5C()
{
  __asm { retn }
}

//----- (0000000180E628D2) ----------------------------------------------------
void __fastcall sub_180E628D2(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  __int64 v14; // rdi
  __int64 v15; // rax
  unsigned int v16; // esi
  char v17; // fl

  BYTE1(v15) = v17;
  _SI = _byteswap_ulong(v16);
  __readeflags();
  _AX = (unsigned __int8)(v15 >> 63) << 11;
  __asm { rcr     ax, 31h }
  v14 = (unsigned int)(__ROR4__(-(int)a12, 1) + 1688828506) + 0x100000000LL;
  __asm
  {
    rcl     si, 0C8h
    retn
  }
}
// 180DBBB03: variable 'v16' is possibly undefined
// 180DBBB1D: variable 'v15' is possibly undefined

//----- (0000000180E637A5) ----------------------------------------------------
void sub_180E637A5()
{
  JUMPOUT(0x180E329A3LL);
}
// 180E26949: control flows out of bounds to 180E329A3

//----- (0000000180E6A9C0) ----------------------------------------------------
__int64 __fastcall sub_180E6A9C0()
{
  int v1; // eax
  __int64 v2; // rdi

  return ((__int64 (*)(void))(v1 + v2))();
}
// 180E6A9C0: variable 'v1' is possibly undefined
// 180D90678: variable 'v2' is possibly undefined
// 180E6A9C0: using guessed type __int64 __fastcall sub_180E6A9C0();

//----- (0000000180E72310) ----------------------------------------------------
void __fastcall sub_180E72310(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  sub_180DDB0F9(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
}

//----- (0000000180E742B6) ----------------------------------------------------
void __fastcall sub_180E742B6()
{
  __asm { retn }
}
// 180E742B7: unbalanced stack, ignored a potential tail call

//----- (0000000180E747D6) ----------------------------------------------------
void sub_180E747D6()
{
  JUMPOUT(0x180DAC8B7LL);
}
// 180E289DB: control flows out of bounds to 180DAC8B7

//----- (0000000180E74C2B) ----------------------------------------------------
void __fastcall sub_180E74C2B(__int64 a1, __int64 a2, __int64 a3)
{
  __asm { retn }
}

//----- (0000000180E7A023) ----------------------------------------------------
void __fastcall sub_180E7A023()
{
  __asm { retn }
}
// 180E7A024: unbalanced stack, ignored a potential tail call

//----- (0000000180E7FB71) ----------------------------------------------------
void __fastcall sub_180E7FB71(
        __int64 a1,
        int a2,
        unsigned __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37)
{
  __int64 v37; // r9

  v37 = a2 + a4;
  if ( a3 <= (unsigned __int64)&a37 )
  {
    __readeflags();
    JUMPOUT(0x180E19F6BLL);
  }
  sub_180DBB85F(a1, a2, a3, v37);
}
// 180E2FB60: control flows out of bounds to 180E19F6B

//----- (0000000180E80D06) ----------------------------------------------------
__int64 __fastcall sub_180E80D06()
{
  __int64 v0; // rsi
  int v1; // r10d

  return ((__int64 (*)(void))(v1 + v0))();
}
// 180E80D06: variable 'v1' is possibly undefined
// 180E80D09: variable 'v0' is possibly undefined
// 180E80D06: using guessed type __int64 __fastcall sub_180E80D06();

//----- (0000000180E8442C) ----------------------------------------------------
void __fastcall sub_180E8442C(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        __int64 a11)
{
  __int64 v14; // rsi
  __int16 v15; // bp
  char v16; // r10
  char v17; // r14

  _R9 = v17;
  LOBYTE(_R9) = ~v17;
  _CL = 0;
  __asm { rcl     r9w, cl }
  _AX = v15 + v16;
  __asm { rcr     ah, 28h }
  v14 = 1 - (((_DWORD)a11 + 1) ^ 0x634A1C34u) + 0x100000000LL;
  __asm { retn }
}
// 180E8444F: variable 'v17' is possibly undefined
// 180DE8522: variable 'v15' is possibly undefined
// 180DE850B: variable 'v16' is possibly undefined

//----- (0000000180E85093) ----------------------------------------------------
__int64 __fastcall sub_180E85093(int a1, __int64 a2, __int64 a3)
{
  return ((__int64 (*)(void))(a1 + a3))();
}

//----- (0000000180E85DDE) ----------------------------------------------------
void __fastcall sub_180E85DDE(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        __int64 a12)
{
  __int64 v12; // rax
  char v13; // r10
  unsigned __int16 v14; // r14
  __int64 v15; // r9
  __int128 v16; // rax

  v15 = v14;
  v16 = v12;
  LOWORD(v15) = _byteswap_ushort(v14);
  BYTE8(v16) = v13;
  sub_180DD7022(a1, *((__int64 *)&v16 + 1), a3, v15, a5, a6, a7, a8, a9, a10, a11, a12);
}
// 180E85E0B: ignored the value written to the shadow area of the succeeding call
// 180E85E06: ignored the value written to the shadow area of the succeeding call
// 180E85E02: ignored the value written to the shadow area of the succeeding call
// 180E85DF9: ignored the value written to the shadow area of the succeeding call
// 180E85DFE: variable 'v14' is possibly undefined
// 180E85E04: variable 'v12' is possibly undefined
// 180E85E12: variable 'v13' is possibly undefined

//----- (0000000180E89304) ----------------------------------------------------
void __fastcall sub_180E89304()
{
  __asm { retn }
}

//----- (0000000180E89724) ----------------------------------------------------
void sub_180E89724()
{
  JUMPOUT(0x180E329A3LL);
}
// 180E26949: control flows out of bounds to 180E329A3

//----- (0000000180E89768) ----------------------------------------------------
__int64 __fastcall sub_180E89768()
{
  __int64 v0; // rdi
  int v1; // esi

  return ((__int64 (*)(void))(v1 + v0))();
}
// 180E89768: variable 'v1' is possibly undefined
// 180E89775: variable 'v0' is possibly undefined
// 180E89768: using guessed type __int64 __fastcall sub_180E89768();

//----- (0000000180E8EA5D) ----------------------------------------------------
void __fastcall sub_180E8EA5D(
        unsigned __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        __int64 a11)
{
  char v11; // di
  __int16 v12; // r10
  bool v13; // zf
  __int64 v14; // rcx

  __readeflags();
  v13 = (unsigned int)_byteswap_uint64(a1) == 1;
  v14 = (unsigned int)v12;
  LOBYTE(v14) = v11;
  if ( !v13 )
    a4 = (unsigned int)v14;
  LOBYTE(a3) = 12;
  sub_180E8442C(v14, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11);
}
// 180E8EA7B: ignored the value written to the shadow area of the succeeding call
// 180E8EA64: variable 'v12' is possibly undefined
// 180E8EA72: variable 'v11' is possibly undefined

//----- (0000000180E9D4DD) ----------------------------------------------------
void __fastcall sub_180E9D4DD(int a1)
{
  __asm { retn }
}

//----- (0000000180EA272B) ----------------------------------------------------
void __fastcall sub_180EA272B()
{
  __asm { retn }
}

//----- (0000000180EA3D48) ----------------------------------------------------
void __fastcall sub_180EA3D48(
        __int64 a1,
        __int64 a2,
        unsigned __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37)
{
  int v37; // r10d
  __int64 v38; // r9

  v38 = v37 + a4;
  if ( a3 <= (unsigned __int64)&a37 )
  {
    __readeflags();
    JUMPOUT(0x180E19F6BLL);
  }
  sub_180DBB85F(a1, a2, a3, v38);
}
// 180E2FB60: control flows out of bounds to 180E19F6B
// 180EA3D48: variable 'v37' is possibly undefined

//----- (0000000180EB5708) ----------------------------------------------------
void sub_180EB5708()
{
  __int64 v0; // r8
  int v1; // [rsp+218h] [rbp+8h]

  __getcallerseflags();
  v0 = _byteswap_ulong((v1 ^ 0x3B0C73AA) + 1) - 518346727 + 0x100000000LL;
  __asm { jmp     r10 }
}

//----- (0000000180EB816D) ----------------------------------------------------
void __fastcall sub_180EB816D(char _CL, __int64 a2, __int64 a3, __int64 (__fastcall **a4)(signed __int64))
{
  signed __int64 v4; // rcx
  void *v5; // rsp
  unsigned int v6; // eax
  __int64 v8; // rsi
  __int64 v10; // rbx
  int v11; // edx
  unsigned int v12; // ecx
  __int64 v16; // [rsp+10h] [rbp-18h] BYREF

  LOBYTE(v8) = v6 ^ v8;
  LOWORD(_EBX) = (__int16)_EBX >> 15;
  v16 = v8;
  __asm { rcl     ebx, cl }
  v10 = v6;
  v11 = v6;
  v12 = 0;
  if ( v6 > 4 )
  {
    v11 = 4;
    v12 = v6 - 4;
  }
  v4 = 8 * v12;
  *(a4 - 1) = (__int64 (__fastcall *)(signed __int64))((char *)a4 + (unsigned int)(8 * v11));
  *(a4 - 2) = (__int64 (__fastcall *)(signed __int64))&v16;
  v5 = alloca(v4);
  if ( v6 )
  {
    do
    {
      if ( (_DWORD)v10 == 1 )
        v4 = (signed __int64)a4[v10];
      v10 = (unsigned int)(v10 - 1);
    }
    while ( (_DWORD)v10 );
  }
  *(_QWORD *)*(a4 - 1) = (*a4)(v4);
  __asm { jmp     rbp }
}
// 180EB816F: variable 'v6' is possibly undefined
// 180EB816F: variable 'v8' is possibly undefined
// 180EB8176: variable '_EBX' is possibly undefined

//----- (0000000180EC1393) ----------------------------------------------------
void sub_180EC1393()
{
  JUMPOUT(0x180E2F0FALL);
}
// 180E00092: control flows out of bounds to 180E2F0FA

//----- (0000000180EC1720) ----------------------------------------------------
void __fastcall sub_180EC1720(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        unsigned __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7,
        __int64 a8,
        __int64 a9,
        __int64 a10,
        __int64 a11,
        __int64 a12,
        __int64 a13,
        __int64 a14,
        __int64 a15,
        __int64 a16,
        __int64 a17,
        __int64 a18,
        __int64 a19,
        __int64 a20,
        __int64 a21,
        __int64 a22,
        __int64 a23,
        __int64 a24,
        __int64 a25,
        __int64 a26,
        __int64 a27,
        __int64 a28,
        __int64 a29,
        __int64 a30,
        __int64 a31,
        __int64 a32,
        __int64 a33,
        __int64 a34,
        __int64 a35,
        __int64 a36,
        __int64 a37,
        __int64 a38,
        __int64 a39,
        __int64 a40)
{
  if ( a4 <= (unsigned __int64)&a40 )
    JUMPOUT(0x180E296C7LL);
  JUMPOUT(0x180E16CB3LL);
}
// 180E50794: control flows out of bounds to 180E296C7
// 180E50764: control flows out of bounds to 180E16CB3

//----- (0000000180EC4263) ----------------------------------------------------
void sub_180EC4263()
{
  JUMPOUT(0x180E7DF3ALL);
}
// 180DCE099: control flows out of bounds to 180E7DF3A

//----- (0000000180EC69CC) ----------------------------------------------------
void __fastcall sub_180EC69CC(__int64 a1, __int64 a2, __int64 a3, __int64 a4, int a5, int a6, __int64 a7)
{
  sub_180D972CB(a1, a2, a3, a4, a5, a6, a7);
}
// 180EC69DA: ignored the value written to the shadow area of the succeeding call
// 180EC69D2: ignored the value written to the shadow area of the succeeding call
// 180EC69CD: ignored the value written to the shadow area of the succeeding call

//----- (0000000180EC6AB5) ----------------------------------------------------
__int64 __fastcall sub_180EC6AB5(__int64 a1, _QWORD *a2)
{
  char v2; // zf
  __int64 v3; // rax
  unsigned __int64 v4; // rcx

  if ( !v2 )
    *--a2 = v3;
  v4 = a1 + 240;
  while ( (unsigned __int64)a2 > v4 )
    *--a2 = nullsub_2;
  return 1LL;
}
// 180EC6AB5: variable 'v2' is possibly undefined
// 180EC6AC2: variable 'v3' is possibly undefined
// 180EC6AB4: using guessed type __int64 __fastcall nullsub_2();

// nfuncs=173 queued=115 decompiled=115 lumina nreq=0 worse=0 better=0
#error "There were 1 decompilation failure(s) on 115 function(s)"
